version: '3.8'
services:
  mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_container:/data/db
    networks:
      chatty:
        aliases:
          - mongo.localtest.me

  va:
    build:
      context: .
      dockerfile: va.Dockerfile
    env_file:
      - chatty.env
    ports:
      - "5005:5005"
    networks:
      chatty:
        aliases:
          - chatty.localtest.me

volumes:
  mongodb_data_container:

networks:
  chatty:
